### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by colorfully-ybf** [jbwang1997/OBBDetection#121]
**Reproduction**
./tools/dist_train.sh configs/obb/fcos_obb/fcos_obb_r50_caffe_fpn_gn-head_4x4_1x_dota10.py 2

**Environment**
the environment uesd to be ok.

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "./tools/train.py", line 153, in <module>
    main()
  File "./tools/train.py", line 149, in main
    meta=meta)
  File "/home/deep/colors/OBBDetection-master/mmdet/apis/train.py", line 133, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/deep/colors/OBBDetection-master/mmdet/core/evaluation/eval_hooks.py", line 64, in after_train_epoch
    if not self.every_n_epochs(runner, self.interval):
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/hooks/hook.py", line 56, in every_n_epochs
    return (runner.epoch + 1) % n == 0 if n > 0 else False
TypeError: '>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "./tools/train.py", line 153, in <module>
    main()
  File "./tools/train.py", line 149, in main
    meta=meta)
  File "/home/deep/colors/OBBDetection-master/mmdet/apis/train.py", line 133, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/deep/colors/OBBDetection-master/mmdet/core/evaluation/eval_hooks.py", line 64, in after_train_epoch
    if not self.every_n_epochs(runner, self.interval):
  File "/home/deep/Libraries/anaconda3/envs/obbdetection/lib/python3.7/site-packages/mmcv/runner/hooks/hook.py", line 56, in every_n_epochs
    return (runner.epoch + 1) % n == 0 if n > 0 else False
TypeError: '>' not supported between instances of 'str' and 'int'

```

**Comment by jbwang1997** [comment]
Could you provide the config by running tools/print_config.py
