### ISSUE TITLE
配置环境，最后一步出现编译问题

### ISSUE THREAD

**Issue by Lujisheng0** [jbwang1997/OBBDetection#170]
Cuda-10.1
pytorch-1.6.0
mmcv-full-1.4.0
环境配置流程：
conda create -n obbdetection python=3.7 -y
conda activate obbdetection
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch
cd OBBDetection
cd BboxToolkit
pip install -v -e .  # or "python setup.py develop"
cd ..
 pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html --no-cache-dir
pip install -r requirements/build.txt
pip install mmpycocotools
pip install -v -e . 
运行最后一句编译出现问题：
(obbdet) [lujs@localhost OBBDetection]$ pip install -v -e .
Using pip 21.2.2 from /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/pip (python 3.7)
Obtaining file:///home/lujs/mmdetection/OBBDetection
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info
    writing /tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-jvabd9s_/mmdet.egg-info/SOURCES.txt'
Requirement already satisfied: matplotlib in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (3.5.2)
Requirement already satisfied: mmcv-full>=1.3 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (1.4.0)
Requirement already satisfied: numpy in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (1.21.5)
Requirement already satisfied: Pillow<=6.2.2 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (6.2.2)
Requirement already satisfied: six in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (1.16.0)
Requirement already satisfied: terminaltables in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (3.1.10)
Requirement already satisfied: torch>=1.3 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (1.6.0)
Requirement already satisfied: torchvision in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmdet==2.2.0+0529d42) (0.7.0)
Requirement already satisfied: opencv-python>=3 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmcv-full>=1.3->mmdet==2.2.0+0529d42) (4.6.0.66)
Requirement already satisfied: addict in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmcv-full>=1.3->mmdet==2.2.0+0529d42) (2.4.0)
Requirement already satisfied: pyyaml in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmcv-full>=1.3->mmdet==2.2.0+0529d42) (6.0)
Requirement already satisfied: yapf in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmcv-full>=1.3->mmdet==2.2.0+0529d42) (0.32.0)
Requirement already satisfied: packaging in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from mmcv-full>=1.3->mmdet==2.2.0+0529d42) (21.3)
Requirement already satisfied: future in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from torch>=1.3->mmdet==2.2.0+0529d42) (0.18.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from matplotlib->mmdet==2.2.0+0529d42) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from matplotlib->mmdet==2.2.0+0529d42) (1.4.3)
Requirement already satisfied: fonttools>=4.22.0 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from matplotlib->mmdet==2.2.0+0529d42) (4.33.3)
Requirement already satisfied: pyparsing>=2.2.1 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from matplotlib->mmdet==2.2.0+0529d42) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from matplotlib->mmdet==2.2.0+0529d42) (0.11.0)
Requirement already satisfied: typing-extensions in /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->mmdet==2.2.0+0529d42) (4.3.0)
Installing collected packages: mmdet
  Running setup.py develop for mmdet
    Running command /home/lujs/anaconda3/envs/obbdet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lujs/mmdetection/OBBDetection/setup.py'"'"'; __file__='"'"'/home/lujs/mmdetection/OBBDetection/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.utils.compiling_info' extension
    Emitting ninja build file /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:252: UserWarning:

                                   !! WARNING !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using c++, and then you can also use
    c++ to compile your extension.

    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                  !! WARNING !!

      platform=sys.platform))
    ninja: no work to do.
    g++ -pthread -B /home/lujs/anaconda3/envs/obbdet/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/lujs/anaconda3/envs/obbdet/compiler_compat -L/home/lujs/anaconda3/envs/obbdet/lib -Wl,-rpath=/home/lujs/anaconda3/envs/obbdet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/mmdet/ops/utils/src/compiling_info.o -L/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/mmdet/ops/utils/compiling_info.cpython-37m-x86_64-linux-gnu.so
    building 'mmdet.ops.nms.nms_ext' extension
    Emitting ninja build file /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:252: UserWarning:

                                   !! WARNING !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using c++, and then you can also use
    c++ to compile your extension.

    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                  !! WARNING !!

      platform=sys.platform))
    [1/1] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/TH -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lujs/anaconda3/envs/obbdet/include/python3.7m -c -c /home/lujs/mmdetection/OBBDetection/mmdet/ops/nms/src/cuda/nms_kernel.cu -o /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/cuda/nms_kernel.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/TH -I/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lujs/anaconda3/envs/obbdet/include/python3.7m -c -c /home/lujs/mmdetection/OBBDetection/mmdet/ops/nms/src/cuda/nms_kernel.cu -o /home/lujs/mmdetection/OBBDetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:5033:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:5054:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:6676:95:   required from here
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
           __p->_M_set_sharable();
           ~~~~~~~~~^~
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:5033:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:5054:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/local/include/c++/7.3.0/bits/basic_string.h:6681:95:   required from here
    /usr/local/include/c++/7.3.0/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
        env=env)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lujs/mmdetection/OBBDetection/setup.py", line 318, in <module>
        zip_safe=False)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
        build_ext.build_extensions(self)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/lujs/anaconda3/envs/obbdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/lujs/anaconda3/envs/obbdet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lujs/mmdetection/OBBDetection/setup.py'"'"'; __file__='"'"'/home/lujs/mmdetection/OBBDetection/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

搞了很久也不知道哪出了问题。Cudnn版本也是和cuda版本对应好的，麻烦作者看看，或者是广大网友看看，谢谢。

**Comment by jassonmakkar** [comment]
Have you or anyone else solved this issue?

**Comment by ZFU123456** [comment]
你解决了吗？

**Comment by Lujisheng0** [comment]
> 你解决了吗？

时间很久了，不记得了，估计还是版本的问题
