### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'GVBBoxHead' object has no attribute 'ratio_on'

### ISSUE THREAD

**Issue by chandlerbing65nm** [jbwang1997/OBBDetection#89]
I have this error when running flops counter on [gliding vertex](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/gliding_vertex/gliding_vertex_r50_fpn_1x_dota10.py).

```
python tools/get_flops.py configs/obb/gliding_vertex/gliding_vertex_r50_fpn_1x_dota10.py --shape 512
```

```
Traceback (most recent call last):  File "tools/get_flops.py", line 62, in <module>    main()  File "tools/get_flops.py", line 52, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/opt/conda/envs/obbdetection0/lib/python3.7/site-packages/mmcv/cnn/utils/flops_counter.py", line 104, in get_model_complexity_info
    _ = flops_model(batch)
  File "/opt/conda/envs/obbdetection0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)  File "/workspace/OBBDetection/mmdet/models/detectors/obb/obb_two_stage.py", line 112, in forward_dummy
    roi_outs = self.roi_head.forward_dummy(x, proposals)
  File "/workspace/OBBDetection/mmdet/models/roi_heads/obb/gv_ratio_roi_head.py", line 22, in forward_dummy
    if self.bbox_head.ratio_on:
  File "/opt/conda/envs/obbdetection0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))torch.nn.modules.module.ModuleAttributeError: 'GVBBoxHead' object has no attribute 'ratio_on'
```

**Comment by jbwang1997** [comment]
Oh, this is a bug in the gliding vertex model, you can directly delete the `if self.bbox_head.ratio_on`.

**Comment by jbwang1997** [comment]
I will fix it in the future commit.
